name: update for specific branch
on:
  push:
    branches-ignore:
      - main

jobs:
  update:
    name: Update Preview Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Publish update
        run: eas update --branch ${{ steps.extract_branch.outputs.branch }} --auto
