name: update for specific branch
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update:
    name: Update Preview Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Publish update
        id: publish-update
        run: |
          update_output=$(eas update --branch ${{ github.head_ref }} --auto --non-interactive --json)
          ios_update_uri=$(echo "$update_output" | jq -r '.[] | select(.platform == "ios") | .manifestPermalink ')
          android_update_uri=$(echo "$update_output" | jq -r '.[] | select(.platform == "android") | .manifestPermalink ')
          echo "::set-output name=ios_update_uri::$ios_update_uri"
          echo "::set-output name=android_update_uri::$android_update_uri"

      - name: Generate iOS QR Code
        uses: snow-actions/qrcode@v1.0.0
        with:
          text: ${{ steps.publish-update.outputs.ios_update_uri }}
          path: ios_uri_qrcode.png

      - name: Generate Android QR Code
        uses: snow-actions/qrcode@v1.0.0
        with:
          text: ${{ steps.publish-update.outputs.android_update_uri }}
          path: android_uri_qrcode.png

      - name: Upload iOS QR Code
        uses: actions/upload-artifact@v1
        with:
          name: ios_uri_qrcode
          path: ios_uri_qrcode.png

      - name: Upload Android QR Code
        uses: actions/upload-artifact@v1
        with:
          name: android_uri_qrcode
          path: android_uri_qrcode.png

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :rocket: Published to Expo Preview Branch: `${{github.head_ref}}`
            Your iOS link is: ${{ steps.publish-update.outputs.ios_update_uri }} :apple:
            Your Android link is: ${{ steps.publish-update.outputs.android_update_uri }} :robot:
